AllCops:
  Exclude:
    - 'berks-cookbooks/**/*'
    - 'knife.rb'
Style/AccessorMethodName:
  Exclude:
    - 'Rakefile'
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'libraries/rightscale_tag_helper.rb'
Lint/IneffectiveAccessModifier:
  Exclude:
    - 'libraries/rightscale_tag_helper.rb'
Style/MultilineBlockChain:
  Exclude:
    - 'libraries/rightscale_tag_helper.rb'
Lint/UselessAccessModifier:
  Exclude:
    - 'libraries/rightscale_tag_helper.rb'
